[WIP] P2300 into_variant implementation to libunifex
facebookexperimental/libunifex pull request #350
Opened 2021-09-17 18:53 UTC by RishabhRD

This PR intends to add implementation of P2300 ``std::execution::into_variant`` implementation to libunifex under name ``unifex::into_variant``

2021-09-19 00:08 UTC, ericniebler requested changes
On the whole, all the pieces are here and this looks very good. Thanks! Your receiver is forwarding the wrong type to the inner receiver. That's the only real problem.

My only other request is that you look more closely at how the rest of libunifex is formatted and match the style, please.

2021-09-19 00:08 UTC, ericniebler commented on include/unifex/into_variant.hpp
> +        std::make_tuple((Values &&)(values)...)));
This isn't quite right. This sends a variant with only a single alternative. The predecessor sender may invoke `set_value` with one of a set of argument types, and this is only one of those. The variant type you compute below in your sender, namely `sender_value_types_t<Predecessor, std::variant, std::tuple>`, is the type of the variant this should be forwarding to the nested receiver. Your sender with have to parameterize this receiver on that type.

2021-09-19 18:19 UTC, RishabhRD commented
Hello @ericniebler , thanks for the comment. I have parameterized the receiver for the variant type as you suggested. I may have gotten it wrong possibly... but I believe you were talking about parameterising receiver class by template. If not please correct me.

Regarding formatting, I have updated the formatting and tried to match the formatting of file ``then.hpp`` as it had similar contents.

2021-09-19 19:09 UTC, ericniebler commented
All correct now, and the formatting looks good too. Thanks.

I notice that we're missing a test of the case where a sender can complete with one of a set of types. You can make such a sender with `just(42) | let_done([]{return just("hello");})`.

2021-09-19 20:17 UTC, RishabhRD commented on test/into_variant_test.cpp
> +  EXPECT_EQ(val, 42);
I wanted to add ``EXPECT_ANY_THROWS(std::get<1>(x.value()));`` to signify that there was only one value in inner variant. However, this breaks the msvc build as [[nodiscard]] warning was treated as error for ``std::get<1>(x.value())``... Hence I removed that assert....

2021-09-19 20:19 UTC, RishabhRD commented
Hello @ericniebler I have added the tests you suggested. I added both static type check and gtest TEST_CASE for that.

2021-09-20 01:10 UTC, ericniebler commented
Great. I just noticed one last thing. These two new files need license headers at the top. Just copy from another file and change the Facebook copyright to yours (if you like).

2021-09-20 13:22 UTC, RishabhRD commented
Hi @ericniebler I added the license header as you suggested.

2021-09-20 14:27 UTC, merged