Fix "include what you use" issues
facebookexperimental/libunifex pull request #439
Opened 2022-07-20 02:47 UTC by ccotter

2022-09-20 01:15 UTC, ispeters requested changes
Thanks for doing this!  The changes look great but it looks like we've diverged since you submitted the PR (sorry for the delay).  If you can resolve the merge conflict, I'll happily merge this.

2022-09-20 02:07 UTC, ccotter commented
For reference, to re-run this check in the future, the following generates standalone translation units that help find include-what-you-use issues. This could be done in the cmake automatically as well, if that's of interest.

```
ls ../include/unifex/ | grep hpp$ | while read header; do printf "#include <unifex/$header>\nint main(){}" > ${header}_test.cpp; done
```

2022-09-21 01:12 UTC, ispeters commented
Thanks, this looks lovely.  Let's see how the CI turns out.

> This could be done in the cmake automatically as well, if that's of interest.

That _sounds_ interesting.  Can you elaborate?  If you're proposing a way to add "check IWYU" to our CI, I think that'd be really valuable.

2022-09-21 03:12 UTC, ispeters approved these changes

2022-09-21 03:13 UTC, merged