Disable continuation visitations by default for binary size savings
facebookexperimental/libunifex pull request #477
Opened 2022-11-22 01:16 UTC by jesswong

~45 kB binary size savings based off a sample app:

Compressed  : -7.0 KiB (-0.16%) => 4.37 MiB
Uncompressed: -44.5 KiB (-0.45%) => 9.67 MiB

2022-11-22 01:40 UTC, jesswong commented
async_trace is failing to build because the type is missing for continuation info. will fix the build errors.

2022-11-23 01:24 UTC, jesswong commented
Ran make && make test when UNIFEX_ENABLE_CONTINUATION_VISITATIONS is true and verified everything still builds and pass.

2022-11-29 19:01 UTC, ispeters requested changes
Looks good, but let's move the definition of `UNIFEX_ENABLE_CONTINUATION_VISITATIONS`.

2022-11-29 19:01 UTC, ispeters commented on examples/async_trace.cpp
> +        #endif
Could we cut a little less deeply?
```suggestion
          std::cout << " " << entry.depth << " [-> " << entry.parentIndex
                    << "]: "
        #if UNIFEX_ENABLE_CONTINUATION_VISITATIONS
                    << entry.continuation.type().name()
        #else
                    << "(continuation typenames disabled)"
        #endif
                    << " @ 0x";
```

2022-11-30 00:03 UTC, ispeters approved these changes
LGTM

2022-11-30 00:13 UTC, merged